version: '3.8'
services:
  app:
    build: .
    container_name: midgard
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["pnpm", "start"]
